# Site settings
title: 我的世界
email: liangziokay@163.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "http://astonz.github.io/" # the subpath of your site, e.g. /blog/
url: "http://astonz.github.io/" # the base hostname & protocol for your site
twitter_username: ""
github_username:  AstonZ

# Build settings
markdown: kramdown

paginate: 4

author: Liang Zhang

gems: [jekyll-paginate]
